version: '3' 
services: 
  apache: 
^    build: 
^^      context: ./apache 
^    ports: 
^^      - "8080:80" 
^    depends_on: 
^^      - php 
^^      - mysql 
^    environment: 
^^      MYSQL_HOST: mysql 
^^      MYSQL_DATABASE: myapp 
^^      MYSQL_USER: ${MYSQL_USER} 
^^      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
  php: 
^    build: 
^^      context: ./php 
^    volumes: 
^^      - ./mi-aplicacion:/var/www/html 
  mysql: 
^    image: mysql:5.7 
^    environment: 
^^      MYSQL_DATABASE: myapp 
^^      MYSQL_USER: ${MYSQL_USER} 
^^      MYSQL_PASSWORD: ${MYSQL_PASSWORD} 
^^      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
^    ports: 
^^      - "3306:3306" 
